import { Contact, Conversation, ChatStatus } from "@/types";

const now = "2025-03-04T15:30:00";

export const conversationContacts: Contact[] = [
  {
    id: "c1",
    name: "Ricardo Mendes",
    phone: "+55 11 98765-4321",
    email: "ricardo@techsys.com.br",
    company: "TechSys Soluções",
    area: "Direito Tributário",
    status: "agendou_consulta",
    origin: "whatsapp",
    assignedTo: "IA Valency",
    lastMessage: "Perfeito, terça às 14h então!",
    lastMessageAt: "2025-03-04T15:20:00",
    createdAt: "2025-03-04T13:30:00",
    tags: ["tributário", "empresa"],
  },
  {
    id: "c2",
    name: "Mariana Costa Silva",
    phone: "+55 21 97654-3210",
    email: "mariana.costa@gmail.com",
    area: "Direito Trabalhista",
    status: "em_qualificacao",
    origin: "google_ads",
    assignedTo: "IA Valency",
    lastMessage: "Fui demitida sem justa causa e não recebi rescisão",
    lastMessageAt: "2025-03-04T15:15:00",
    createdAt: "2025-03-04T14:50:00",
    tags: ["trabalhista", "rescisão"],
  },
  {
    id: "c3",
    name: "Fernando Oliveira",
    phone: "+55 11 96543-2109",
    email: "fernando.oli@outlook.com",
    company: "Oliveira & Filhos Ltda",
    area: "Direito Empresarial",
    status: "qualificado",
    origin: "indicacao",
    assignedTo: "Dr. Carlos",
    lastMessage: "Dr. Carlos, obrigado pelas orientações. Vou reunir os documentos.",
    lastMessageAt: "2025-03-04T14:30:00",
    createdAt: "2025-03-02T09:00:00",
    tags: ["empresarial", "societário"],
  },
  {
    id: "c4",
    name: "Patrícia Almeida",
    phone: "+55 31 99876-5432",
    email: "patricia.alm@email.com",
    area: "Direito de Família",
    status: "em_qualificacao",
    origin: "instagram",
    assignedTo: "IA Valency",
    lastMessage: "Preciso de ajuda com processo de guarda compartilhada",
    lastMessageAt: "2025-03-04T14:10:00",
    createdAt: "2025-03-04T13:45:00",
    tags: ["família", "guarda"],
  },
  {
    id: "c5",
    name: "Carlos Eduardo Santos",
    phone: "+55 11 95432-1098",
    company: "Santos Comércio",
    area: "Direito do Consumidor",
    status: "desqualificado",
    origin: "whatsapp",
    assignedTo: "IA Valency",
    lastMessage: "Achei caro, vou ver outras opções",
    lastMessageAt: "2025-03-04T12:00:00",
    createdAt: "2025-03-04T10:30:00",
    tags: ["consumidor"],
  },
  {
    id: "c6",
    name: "Ana Beatriz Lima",
    phone: "+55 21 94321-0987",
    email: "anabeatriz@email.com",
    area: "Direito Trabalhista",
    status: "agendou_consulta",
    origin: "site",
    assignedTo: "IA Valency",
    lastMessage: "Confirmado! Quinta às 10h.",
    lastMessageAt: "2025-03-04T11:40:00",
    createdAt: "2025-03-03T16:00:00",
    tags: ["trabalhista", "assédio"],
  },
  {
    id: "c7",
    name: "Roberto Nascimento Jr.",
    phone: "+55 11 93210-9876",
    email: "roberto.jr@empresa.com",
    company: "Nascimento Engenharia",
    area: "Direito Civil",
    status: "proposta_procedimento",
    origin: "indicacao",
    assignedTo: "IA Valency",
    lastMessage: "Recebi a proposta, vou analisar com meu sócio.",
    lastMessageAt: "2025-03-04T10:20:00",
    createdAt: "2025-02-28T14:00:00",
    tags: ["cível", "contrato"],
  },
  {
    id: "c8",
    name: "Juliana Ferreira",
    phone: "+55 31 92109-8765",
    email: "ju.ferreira@hotmail.com",
    area: "Direito Previdenciário",
    status: "fechou_cirurgia",
    origin: "google_ads",
    assignedTo: "Dra. Carla",
    lastMessage: "Contrato assinado! Obrigada pela agilidade.",
    lastMessageAt: "2025-03-04T09:30:00",
    createdAt: "2025-02-25T10:00:00",
    tags: ["previdenciário", "aposentadoria"],
  },
  {
    id: "c9",
    name: "Thiago Barbosa",
    phone: "+55 11 91098-7654",
    area: "Direito Criminal",
    status: "novo",
    origin: "whatsapp",
    assignedTo: "IA Valency",
    lastMessage: "Oi, boa tarde",
    lastMessageAt: "2025-03-04T15:28:00",
    createdAt: "2025-03-04T15:28:00",
    tags: [],
  },
  {
    id: "c10",
    name: "Camila Rodrigues",
    phone: "+55 21 90987-6543",
    email: "camila.r@gmail.com",
    company: "Studio Design",
    area: "Direito Tributário",
    status: "qualificado",
    origin: "instagram",
    assignedTo: "IA Valency",
    lastMessage: "Sim, tenho interesse. Quando posso agendar?",
    lastMessageAt: "2025-03-04T13:50:00",
    createdAt: "2025-03-03T11:00:00",
    tags: ["tributário", "MEI"],
  },
];

const chatStatuses: Record<string, ChatStatus> = {
  c1: "agendando",
  c2: "qualificando",
  c3: "finalizado",
  c4: "qualificando",
  c5: "finalizado",
  c6: "agendando",
  c7: "aguardando",
  c8: "finalizado",
  c9: "qualificando",
  c10: "agendando",
};

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    contact: conversationContacts[0],
    unreadCount: 0,
    isAI: true,
    chatStatus: chatStatuses.c1,
    timeline: [
      { id: "t1", label: "Lead recebido via WhatsApp", timestamp: "2025-03-04T13:30:00" },
      { id: "t2", label: "IA iniciou qualificação", timestamp: "2025-03-04T13:31:00" },
      { id: "t3", label: "Lead qualificado", timestamp: "2025-03-04T14:45:00" },
      { id: "t4", label: "Reunião agendada para 18/03 às 14h", timestamp: "2025-03-04T15:20:00" },
    ],
    messages: [
      { id: "m1-1", content: "Oi, vi o anúncio de vocês sobre consultoria tributária", sender: "contact", timestamp: "2025-03-04T13:30:00", status: "read" },
      { id: "m1-2", content: "Olá Ricardo! Que bom receber seu contato. Sim, trabalhamos com consultoria tributária para empresas. Para eu entender melhor como posso te ajudar, você poderia me contar um pouco sobre sua empresa?", sender: "ai", timestamp: "2025-03-04T13:31:00", status: "read" },
      { id: "m1-3", content: "Tenho uma empresa de tecnologia com 45 funcionários, estamos gastando muito com impostos", sender: "contact", timestamp: "2025-03-04T13:45:00", status: "read" },
      { id: "m1-4", content: "Entendo, Ricardo. Empresas de tecnologia frequentemente têm oportunidades significativas de otimização tributária. Com 45 colaboradores, vocês provavelmente podem se beneficiar de incentivos como a Lei do Bem e otimização do enquadramento tributário. Nosso especialista Dr. Fernando pode avaliar o cenário fiscal da sua empresa. Posso agendar uma reunião com ele?", sender: "ai", timestamp: "2025-03-04T13:46:00", status: "read" },
      { id: "m1-5", content: "Sim, pode ser na próxima terça", sender: "contact", timestamp: "2025-03-04T14:50:00", status: "read" },
      { id: "m1-6", content: "Perfeito! Tenho disponibilidade na terça-feira, dia 18/03, nos seguintes horários: 10h, 14h ou 16h. Qual funciona melhor para você?", sender: "ai", timestamp: "2025-03-04T14:51:00", status: "read" },
      { id: "m1-7", content: "Perfeito, terça às 14h então!", sender: "contact", timestamp: "2025-03-04T15:20:00", status: "read" },
      { id: "m1-8", content: "Confirmado! Reunião agendada com Dr. Fernando para terça-feira, 18/03, às 14h. Vou enviar o link da videochamada por aqui. Até lá, Ricardo!", sender: "ai", timestamp: "2025-03-04T15:21:00", status: "delivered" },
    ],
  },
  {
    id: "conv-2",
    contact: conversationContacts[1],
    unreadCount: 2,
    isAI: true,
    chatStatus: chatStatuses.c2,
    timeline: [
      { id: "t1", label: "Lead recebido via Google Ads", timestamp: "2025-03-04T14:50:00" },
      { id: "t2", label: "IA iniciou qualificação", timestamp: "2025-03-04T14:51:00" },
    ],
    messages: [
      { id: "m2-1", content: "Olá, preciso de um advogado trabalhista urgente", sender: "contact", timestamp: "2025-03-04T14:50:00", status: "read" },
      { id: "m2-2", content: "Olá Mariana! Entendo a urgência. Somos especializados em Direito Trabalhista e vamos te ajudar. Pode me contar o que aconteceu?", sender: "ai", timestamp: "2025-03-04T14:51:00", status: "read" },
      { id: "m2-3", content: "Fui demitida sem justa causa e não recebi rescisão", sender: "contact", timestamp: "2025-03-04T15:15:00", status: "delivered" },
      { id: "m2-4", content: "Sinto muito por essa situação, Mariana. A não quitação da rescisão no prazo é uma violação da CLT. Você tem direito a receber multa por atraso além dos valores rescisórios. Há quanto tempo você foi desligada?", sender: "ai", timestamp: "2025-03-04T15:16:00", status: "delivered" },
    ],
  },
  {
    id: "conv-3",
    contact: conversationContacts[2],
    unreadCount: 0,
    isAI: false,
    chatStatus: chatStatuses.c3,
    timeline: [
      { id: "t1", label: "Lead recebido via indicação", timestamp: "2025-03-02T09:00:00" },
      { id: "t2", label: "IA qualificou lead", timestamp: "2025-03-02T09:15:00" },
      { id: "t3", label: "Dr. Carlos assumiu conversa", timestamp: "2025-03-02T10:00:00" },
      { id: "t4", label: "Lead qualificado", timestamp: "2025-03-03T11:00:00" },
    ],
    messages: [
      { id: "m3-1", content: "Bom dia, o Pedro Alves me indicou vocês. Preciso de assessoria para reestruturação societária", sender: "contact", timestamp: "2025-03-02T09:00:00", status: "read" },
      { id: "m3-2", content: "Bom dia Fernando! Obrigada pela confiança na indicação do Pedro. Reestruturação societária é uma de nossas especialidades. Vou conectar você com o Dr. Carlos, nosso especialista em direito empresarial.", sender: "ai", timestamp: "2025-03-02T09:01:00", status: "read" },
      { id: "m3-3", content: "Fernando, bom dia! Sou o Dr. Carlos. O Pedro é um grande amigo. Me conta: vocês estão pensando em alterar o contrato social ou é algo mais complexo, como fusão ou cisão?", sender: "human", timestamp: "2025-03-02T10:00:00", status: "read" },
      { id: "m3-4", content: "Dr. Carlos, é uma cisão parcial. Queremos separar a parte de engenharia civil da consultoria", sender: "contact", timestamp: "2025-03-02T10:30:00", status: "read" },
      { id: "m3-5", content: "Entendi perfeitamente. Cisão parcial tem suas particularidades, especialmente no aspecto tributário e na sucessão de obrigações. Vou preparar uma análise preliminar e te envio até amanhã.", sender: "human", timestamp: "2025-03-02T10:35:00", status: "read" },
      { id: "m3-6", content: "Dr. Carlos, obrigado pelas orientações. Vou reunir os documentos.", sender: "contact", timestamp: "2025-03-04T14:30:00", status: "read" },
    ],
  },
  {
    id: "conv-4",
    contact: conversationContacts[3],
    unreadCount: 1,
    isAI: true,
    chatStatus: chatStatuses.c4,
    timeline: [
      { id: "t1", label: "Lead recebido via Instagram", timestamp: "2025-03-04T13:45:00" },
      { id: "t2", label: "IA iniciou qualificação", timestamp: "2025-03-04T13:46:00" },
    ],
    messages: [
      { id: "m4-1", content: "Oi! Vi o post de vocês sobre direito de família", sender: "contact", timestamp: "2025-03-04T13:45:00", status: "read" },
      { id: "m4-2", content: "Olá Patrícia! Sim, somos especializados em Direito de Família. Como posso ajudar?", sender: "ai", timestamp: "2025-03-04T13:46:00", status: "read" },
      { id: "m4-3", content: "Preciso de ajuda com processo de guarda compartilhada", sender: "contact", timestamp: "2025-03-04T14:10:00", status: "delivered" },
      { id: "m4-4", content: "Entendo, Patrícia. A guarda compartilhada é a modalidade preferencial da legislação brasileira. Para te orientar melhor, preciso entender: vocês já têm um acordo informal ou seria a primeira definição judicial?", sender: "ai", timestamp: "2025-03-04T14:11:00", status: "delivered" },
    ],
  },
  {
    id: "conv-5",
    contact: conversationContacts[4],
    unreadCount: 0,
    isAI: true,
    chatStatus: chatStatuses.c5,
    timeline: [
      { id: "t1", label: "Lead recebido via WhatsApp", timestamp: "2025-03-04T10:30:00" },
      { id: "t2", label: "IA iniciou qualificação", timestamp: "2025-03-04T10:31:00" },
      { id: "t3", label: "Lead desqualificado — preço", timestamp: "2025-03-04T12:00:00" },
    ],
    messages: [
      { id: "m5-1", content: "Quanto custa uma consulta?", sender: "contact", timestamp: "2025-03-04T10:30:00", status: "read" },
      { id: "m5-2", content: "Olá Carlos! Nossos valores variam conforme a complexidade do caso. Para que eu possa dar uma estimativa, poderia me contar brevemente sobre sua demanda?", sender: "ai", timestamp: "2025-03-04T10:31:00", status: "read" },
      { id: "m5-3", content: "Quero processar uma loja que vendeu produto com defeito", sender: "contact", timestamp: "2025-03-04T10:45:00", status: "read" },
      { id: "m5-4", content: "Entendo. Casos de direito do consumidor por vício do produto são bem comuns. Nossa consulta inicial para avaliar o caso é R$ 350, já com análise documental. Se decidir prosseguir, descontamos da primeira parcela dos honorários.", sender: "ai", timestamp: "2025-03-04T10:46:00", status: "read" },
      { id: "m5-5", content: "Achei caro, vou ver outras opções", sender: "contact", timestamp: "2025-03-04T12:00:00", status: "read" },
      { id: "m5-6", content: "Sem problemas, Carlos! Caso reconsidere, estamos à disposição. Nosso diferencial é a agilidade na resolução — muitos casos de consumidor resolvemos em até 60 dias. Boa sorte!", sender: "ai", timestamp: "2025-03-04T12:01:00", status: "read" },
    ],
  },
  {
    id: "conv-6",
    contact: conversationContacts[5],
    unreadCount: 0,
    isAI: true,
    chatStatus: chatStatuses.c6,
    timeline: [
      { id: "t1", label: "Lead recebido via site", timestamp: "2025-03-03T16:00:00" },
      { id: "t2", label: "IA qualificou lead", timestamp: "2025-03-03T16:30:00" },
      { id: "t3", label: "Reunião agendada para 20/03 às 10h", timestamp: "2025-03-04T11:40:00" },
    ],
    messages: [
      { id: "m6-1", content: "Boa tarde, gostaria de saber sobre ações trabalhistas contra assédio moral", sender: "contact", timestamp: "2025-03-03T16:00:00", status: "read" },
      { id: "m6-2", content: "Boa tarde, Ana Beatriz! Assédio moral no ambiente de trabalho é uma situação muito séria e que merece atenção jurídica. Você está passando por isso atualmente ou já foi desligada?", sender: "ai", timestamp: "2025-03-03T16:01:00", status: "read" },
      { id: "m6-3", content: "Estou passando por isso agora no trabalho. Meu chefe faz comentários constrangedores em público", sender: "contact", timestamp: "2025-03-03T16:10:00", status: "read" },
      { id: "m6-4", content: "Sinto muito, Ana Beatriz. Isso configura assédio moral e você tem respaldo legal. Recomendo que você documente tudo: grave conversas (se possível), salve e-mails, anote datas. Gostaria de agendar uma consulta com nossa especialista Dra. Carla?", sender: "ai", timestamp: "2025-03-03T16:11:00", status: "read" },
      { id: "m6-5", content: "Sim, por favor. Quando tem horário?", sender: "contact", timestamp: "2025-03-04T11:30:00", status: "read" },
      { id: "m6-6", content: "Temos horários na quinta-feira, 20/03: 10h, 11h ou 15h. Qual prefere?", sender: "ai", timestamp: "2025-03-04T11:31:00", status: "read" },
      { id: "m6-7", content: "Confirmado! Quinta às 10h.", sender: "contact", timestamp: "2025-03-04T11:40:00", status: "read" },
    ],
  },
  {
    id: "conv-7",
    contact: conversationContacts[6],
    unreadCount: 0,
    isAI: true,
    chatStatus: chatStatuses.c7,
    timeline: [
      { id: "t1", label: "Lead recebido via indicação", timestamp: "2025-02-28T14:00:00" },
      { id: "t2", label: "Lead qualificado", timestamp: "2025-02-28T15:00:00" },
      { id: "t3", label: "Reunião realizada", timestamp: "2025-03-03T10:00:00" },
      { id: "t4", label: "Proposta enviada", timestamp: "2025-03-03T16:00:00" },
    ],
    messages: [
      { id: "m7-1", content: "Boa tarde, o José da construtora XYZ me indicou. Preciso revisar contratos com fornecedores", sender: "contact", timestamp: "2025-02-28T14:00:00", status: "read" },
      { id: "m7-2", content: "Boa tarde, Roberto! A indicação do José é uma honra. Revisão contratual é fundamental para proteger sua empresa. Quantos contratos precisariam ser revisados aproximadamente?", sender: "ai", timestamp: "2025-02-28T14:01:00", status: "read" },
      { id: "m7-3", content: "Uns 12 contratos com fornecedores e 3 com clientes grandes", sender: "contact", timestamp: "2025-02-28T14:15:00", status: "read" },
      { id: "m7-4", content: "Recebi a proposta, vou analisar com meu sócio.", sender: "contact", timestamp: "2025-03-04T10:20:00", status: "read" },
      { id: "m7-5", content: "Perfeito, Roberto! Fique à vontade para tirar qualquer dúvida. Estamos à disposição.", sender: "ai", timestamp: "2025-03-04T10:21:00", status: "delivered" },
    ],
  },
  {
    id: "conv-8",
    contact: conversationContacts[7],
    unreadCount: 0,
    isAI: false,
    chatStatus: chatStatuses.c8,
    timeline: [
      { id: "t1", label: "Lead recebido via Google Ads", timestamp: "2025-02-25T10:00:00" },
      { id: "t2", label: "IA qualificou lead", timestamp: "2025-02-25T10:30:00" },
      { id: "t3", label: "Dra. Carla assumiu conversa", timestamp: "2025-02-26T09:00:00" },
      { id: "t4", label: "Contrato assinado", timestamp: "2025-03-04T09:30:00" },
    ],
    messages: [
      { id: "m8-1", content: "Bom dia, gostaria de saber sobre aposentadoria especial para quem trabalhou com insalubridade", sender: "contact", timestamp: "2025-02-25T10:00:00", status: "read" },
      { id: "m8-2", content: "Bom dia, Juliana! Aposentadoria especial é um direito de quem trabalhou exposto a agentes nocivos. Vou te conectar com a Dra. Carla, nossa especialista em Direito Previdenciário.", sender: "ai", timestamp: "2025-02-25T10:01:00", status: "read" },
      { id: "m8-3", content: "Juliana, bom dia! Sou a Dra. Carla. Para aposentadoria especial precisamos comprovar a exposição. Você tem o PPP (Perfil Profissiográfico Previdenciário) da empresa?", sender: "human", timestamp: "2025-02-26T09:00:00", status: "read" },
      { id: "m8-4", content: "Contrato assinado! Obrigada pela agilidade.", sender: "contact", timestamp: "2025-03-04T09:30:00", status: "read" },
    ],
  },
  {
    id: "conv-9",
    contact: conversationContacts[8],
    unreadCount: 1,
    isAI: true,
    chatStatus: chatStatuses.c9,
    timeline: [
      { id: "t1", label: "Lead recebido via WhatsApp", timestamp: "2025-03-04T15:28:00" },
      { id: "t2", label: "IA iniciou qualificação", timestamp: "2025-03-04T15:28:00" },
    ],
    messages: [
      { id: "m9-1", content: "Oi, boa tarde", sender: "contact", timestamp: "2025-03-04T15:28:00", status: "delivered" },
      { id: "m9-2", content: "Boa tarde! Seja bem-vindo ao escritório Valency. Sou a assistente virtual. Em que posso ajudar?", sender: "ai", timestamp: "2025-03-04T15:28:30", status: "delivered" },
    ],
  },
  {
    id: "conv-10",
    contact: conversationContacts[9],
    unreadCount: 0,
    isAI: true,
    chatStatus: chatStatuses.c10,
    timeline: [
      { id: "t1", label: "Lead recebido via Instagram", timestamp: "2025-03-03T11:00:00" },
      { id: "t2", label: "IA qualificou lead", timestamp: "2025-03-03T12:00:00" },
    ],
    messages: [
      { id: "m10-1", content: "Oi! Sou MEI e quero migrar para ME. Podem me ajudar?", sender: "contact", timestamp: "2025-03-03T11:00:00", status: "read" },
      { id: "m10-2", content: "Olá Camila! Claro, essa transição de MEI para ME é bem comum quando o faturamento cresce. Podemos te ajudar com todo o processo tributário e contábil. Qual seu faturamento atual aproximado?", sender: "ai", timestamp: "2025-03-03T11:01:00", status: "read" },
      { id: "m10-3", content: "Estou faturando cerca de R$ 15 mil por mês", sender: "contact", timestamp: "2025-03-03T11:20:00", status: "read" },
      { id: "m10-4", content: "Ótimo, Camila! Com esse faturamento, a migração para ME é realmente o caminho. Podemos avaliar o melhor regime tributário — Simples Nacional, Lucro Presumido — para otimizar seus impostos. Gostaria de agendar uma consulta?", sender: "ai", timestamp: "2025-03-03T11:21:00", status: "read" },
      { id: "m10-5", content: "Sim, tenho interesse. Quando posso agendar?", sender: "contact", timestamp: "2025-03-04T13:50:00", status: "read" },
    ],
  },
];
